apiVersion: v1
kind: ConfigMap
metadata:
  name: vulnshield-config
  namespace: vulnshield
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "vulnshield"
  POSTGRES_USER: "vulnshield"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "vulnshield"
  RABBITMQ_VHOST: "vulnshield"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "vulnshield-evidence"
  MINIO_USE_SSL: "false"
  LLM_PROVIDER: "ollama"
  OLLAMA_BASE_URL: "http://ollama:11434"
  OLLAMA_MODEL: "llama3.2"
  NEXT_PUBLIC_API_URL: "http://api-gateway:8080/api/v1"

---
apiVersion: v1
kind: Secret
metadata:
  name: vulnshield-secrets
  namespace: vulnshield
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me-in-production"
  RABBITMQ_PASSWORD: "change-me-in-production"
  JWT_SECRET: "change-me-jwt-secret-key-min-32-chars"
  MINIO_ACCESS_KEY: "vulnshield_minio"
  MINIO_SECRET_KEY: "change-me-minio-secret"
